### ISSUE TITLE
broadcast_data Segfault

### ISSUE THREAD

**Issue by ksmith0** [pixie16/PixieSuite2#1]
A seg fault occurs when not in pacman or shm mode and acquiring data to disk with the run command. Upon the first spill a seg fault occurs. Removing line 1146 of hirbf_buffers.cpp `output[bytes] = '\0';` which sets a undefined address as `output` is only declared `bytes` large `output = new char[bytes];` @cthornsb What is the purpose of this? Should it be set to bytes-1 or should the array be declared with one extra unit long? The blame makes this look like a problem that has been around for sometime (April), but has just reared its ugly head.

**Comment by cthornsb** [comment]
Fixed in commit feca389.
