### ISSUE TITLE
Buffer sizes too big on NiTemp

### ISSUE THREAD

**Issue by wapmanzoo** [pixie16/PixieSuite2#100]
The issue already exists on there, but I have never been able to reproduce the problem. 

For the short term, you should consider using poll2 with pacman mode. That way you are not reliant on my buffer writers/readers.

Cory

On 08/03/2016 12:44 PM, William Peters wrote:
Cory,
  OK. I made a gihub account. I'm waiting for some email confirmation before I can create an issue in the PIXIESUITE2 repository.

Strange that it is only with this computer. Also strange that it was working (maybe with root only) just a couple months ago.

-Bill

William A. Peters
University of Tennessee
Oak Ridge National Lab

ORNL, Physics Division
P.O. Box 2008 M.S. 6373
Bld. 6000, Rm. 103
Oak Ridge, TN 37831
(865) 576-6598

On Wed, Aug 3, 2016 at 12:42 PM, Cory Thornsberry corythornsberry@gmail.com wrote:
Oh. When you said the header, I thought you meant the "HEAD" buffer. Okay, then I agree with what you were saying. Unfortunately, I don't think there is a way to force scanor to read the file if the data buffers are too large. Stan is working on paass which implements my buffer readers, but I'm not sure what the status of that currently is. The only thing I can think to do is to manually delete the excess bytes from the data file. This is how Karl "fixed" the one or two corrupted files from your run last year. But that is not feasible for large files. I will talk to Stan and Karl once they get back from lunch and see what they think.

P.S. I looked at some of the ldf files from ND a few weeks ago and they look fine. The DATA buffers are not overfilled. All the ones I checked had exactly 8194 words.

Cory

On 08/03/2016 12:35 PM, William Peters wrote:
Cory,
   Yes these are from nitemp. It seemed to us that the second header was in the wrong place, which makes sense with what you are saying because if the buffer is too large than the next header will be misplaced (compared to a header placement for normal 8194 words).

Is there a suggestion for getting the scan code to read this and make a his file?

The version of PixieSuite was yesterday's "master".

The version of pixie scan was yesterday's "dev" (I think).

I'll send a screen shot of the version from POLL2.

-Bill

William A. Peters
University of Tennessee
Oak Ridge National Lab

ORNL, Physics Division
P.O. Box 2008 M.S. 6373
Bld. 6000, Rm. 103
Oak Ridge, TN 37831
(865) 576-6598

On Wed, Aug 3, 2016 at 12:07 PM, Cory Thornsberry corythornsberry@gmail.com wrote:
Hello,

The header looks fine to me. I can read it with the ldfReader tool. The issue is that this version of poll2, for whatever reason, is massively overfilling the DATA buffers. My scan code can read it fine because it isn't looking for a fixed buffer size. But scanor just completely gives up when it encounters one of these things. I'm going to include a couple screenshots from my hex reader program. These will probably make more sense to Karl, but it makes it clear what the actual problem is.

The DATA buffers look okay, other than the size. My scan code correctly decodes everything and I can see counts from mod 0 chan 0. You can see that the first data buffer has a total size of 9270 words (it's supposed to be 8194). The second data buffer has the exact same size, 9270 words. 

I have never encountered this problem except on data files written on that computer (I'm assuming these were done on nitemp). What version of PixieSuite2 is on the computer you guys were using? Also, what branch are you guys using. You said master, but is it up to date?

Cory

On 08/02/2016 09:11 PM, William Peters wrote:
Cory,
   Karl and Marija and I spent about half the day trying to fix some bug in how POLL2 (master version) was writing an ldf file. It seems the buffer heard is getting inserted into the buffer body and the second buffer then doesn't have a proper header and the scan crashes. Karl updated the scan code and the POLL2 this afternoon to the latest versions. It is odd that the error is occurring now when some people were using it recently with no problems. I'm attaching a sample ldf that we took this afternoon. We are hoping you could take a look and maybe help me fix the issue. I'm using the MCA feature to test some detectors for now, but will need to save and scan soon.

Let me know if there's more info you need.

-Bill

**Comment by ksmith0** [comment]
This is related to issue #45
