### ISSUE TITLE
RevF - Large Deadtime when using PACMAN Mode

### ISSUE THREAD

**Issue by spaulaus** [pixie16/PixieSuite2#19]
There are huge deadtime effects when running poll2 in PACMAN mode. This was reported during the ISOLDE experiments. Attached are two screen captures of histogram 1811, which records the run time in ms. 
## Taken with poll2

![poll2pac-is599oct_a052_hrs_05](https://cloud.githubusercontent.com/assets/1553042/10262924/4c699fdc-69aa-11e5-92fe-179de19b2e0d.png)
## Taken with poll

![pollpac-is599oct_a052_hrs_06](https://cloud.githubusercontent.com/assets/1553042/10262923/4c68454c-69aa-11e5-85e7-bbcc5b607ce6.png)

**Comment by spaulaus** [comment]
Could this be related to the waiting for the pacman commands? The commands are on a different thread than the polling process, correct? This may not be the cause, but it's the only idea I have right now.

**Comment by ksmith0** [comment]
Can you check that they do indeed have the pacman command check on a separate thread. Also, could you take some data with poll2 out of pacman mode. Is it possible that the poll broadcast / receive is missing packets?

**Comment by ksmith0** [comment]
This is an issue with UDP. Reducing the polling threshold to 10% resolved this issue at ISOLDE. Marking this as wontfix as we cannot change the way pacman takes data. If this crops up during an experiment the threshold should be reduced.

**Comment by spaulaus** [comment]
I am reopening this issue since we're spending time investigating it. We still won't fix it, but we are at least investigating a workaround.

I have confirmed that the drops in the data are correlated with the scan code not being able to reconstruct a buffer. 

```
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE  INCOMPLETE BUFFER 7
 I/B [  26 of 19 : pos 6632    1733 total spills
| 3f54 13  10 e710e6e
| 4294967295 4294967295  4294967295 4294967295
```

The number of Incomplete Buffer message corresponds to the number of gaps that we have in the data:
![is599oct_a051_03-1](https://cloud.githubusercontent.com/assets/1553042/10607805/160987b4-770a-11e5-9d60-829500fa7fd8.png)

In addition, we have the error message:

```
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE  INCOMPLETE BUFFER 4
  831 valid spills so far. Starting fresh spill.
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE NWORDS 0
SANITY CHECK FAILED: lenRec = 244453023, vsn = 243469961, inWords = 0 of 67236, outWords = 0
   >>> buffer = 1000, user time = 10.65, system time = 0.11, real
      time = 10.85, ts = 8.62422e+12                           
Buffer skipped, Last: 0 of 19 buffers read -- Now: 6
```

If the time listed (10.85 s) we are in the first row (0) where there isn't a drop to 0 counts. If we go by the count of Incomplete buffers we're in row 11. More food to chew on. 

The data analyzed was on kqxhc using the data file: IS599Oct_A051_03-1.ldf. The data was taken at the ISOLDE IS599 experiment using poll2 in pacman mode. The fifo threshold used cannot be confirmed.

**Comment by ksmith0** [comment]
I'm closing this as it is marked wontfix.
