### ISSUE TITLE
broadcast_pac_data

### ISSUE THREAD

**Issue by ksmith0** [pixie16/PixieSuite2#20]
When broadcasting pac data if the size is of the data is larger than the `MAX_PKT_DATA` the first packet sent does not obey the AcqBuf header, but instead overwrites it as if it is a continuation packet. I believe we should rewrite this routine such that the deadtime accounting due to UDP losses is properly accounted for by pacman.

**Comment by spaulaus** [comment]
I'm not sure that we need to fix this issue. It's a "feature" of pacman and outside the scope of this project.

**Comment by ksmith0** [comment]
We could correct the broadcast such that the packet loss statements in pacman are correct. I think I can do this with a small investment of time. The broadcast_pac_data routine of PixieSuite does not follow the system established by the pacman routines.
