### ISSUE TITLE
Gnuplot with get_traces

### ISSUE THREAD

**Issue by spaulaus** [pixie16/PixieSuite2#22]
The get_traces program output can be transferred directly into gnuplot from c++. We should look at using this to display the data.

**Comment by spaulaus** [comment]
A workaround has already been completed for this.

**Comment by ksmith0** [comment]
The work around does not mean this is resolved. Are you saying you would no longer like to have integrated c++ plotting?

**Comment by spaulaus** [comment]
That is correct, the workaround that you have put in place is a perfectly acceptable solution. We could potentially add this back in later, but I do not see that it should even be on our radar.
