### ISSUE TITLE
Trace Viewer

### ISSUE THREAD

**Issue by spaulaus** [pixie16/PixieSuite2#6]
We need to re-implement the gnuplot trace viewing scripts. The scripts are not in intuitive or useful locations at the moment, and the trace capture program is not built by default.

**Comment by ksmith0** [comment]
This was reimplimented in commit 4b6934a07a53b9a585393200f8128cd7b3c8ee80 as a program called viewBaseline. Also, an online scope program was built in commit f11343b415ae94cd0fecbb540641691d5db91795 and the most recent version is available in commit 6717c49c7cb910ee1aaba81c7663472bbdec57e6.
