### ISSUE TITLE
Update installation via cmake

### ISSUE THREAD

**Issue by spaulaus** [pixie16/PixieSuite2#65]
The default installation location for the program should be updated to have the following scheme:

```
$INSTALL_PATH/include
$INSTALL_PATH/bin
$INSTALL_PATH/lib
$INSTALL_PATH/share
```

The share folder should include the default pixie.cfg, slot_def.set and default.set files.
This allows us to locate the entire scheme in the /opt directory for simple installation to multiple users.

**Comment by ksmith0** [comment]
This was resolved in commit 4b6934a07a53b9a585393200f8128cd7b3c8ee80 and c61231e1.
