### ISSUE TITLE
Issues Installing Poll2 on JINR computers (w/SVP)

### ISSUE THREAD

**Issue by ntbrewer** [pixie16/PixieSuite2#83]
Version Info:
CENTOS 6.2 | 2.6.32-220.7.1.el6.x86_64   | 2.8.12.2-4.el6 | 4.4.6 20110731 (Red Hat 4.4.6-3)

with _plx6.40 version
Pixie16RevD_General_1.4.3_Update_04072011

pixie.cfg:
PixieBaseDir      /opt/xia/current
SpFpgaFile        firmware/fippixie16_revdgeneral_r16623.bin
ComFpgaFile       firmware/syspixie16_revdgeneral_r20408.bin
TrigFpgaFile      firmware/pixie16trigger.bin
DspConfFile       dsp/Pixie16DSP_r18419.ldr
DspVarFile        dsp/Pixie16DSP_r18419.var
DspSetFile        ./OfflineDubna.set
CrateConfig       ./pxisys.ini
# DspSetFile        configuration/default.set

DspWorkingSetFile ./OfflineDubna.set
ListModeFile      ./listmode.dat
SlotFile          ./slot_def.set
# SlotFile          ./slot_def.set
# AltComFpgaFile    firmware/syspixie16_revdgeneral_r20408.bin
# AltDspConfFile    dsp/Pixie16DSP_revd_ornl_she_r22025.ldr
# AltDspVarFile     dsp/Pixie16DSP_revd_ornl_she_r22025.var
# AltSpFpgaFile     firmware/fippixie16_revd_ornl_she_r21208.bin
# AltTrigFpgaFile   firmware/pixie16trigger.bin

pixie.cfg (END) 
1. Known ERROR:

/home/pixie16/Programs/PixieSuite2/Interface/source/PixieSupport.cpp: In member function ‘virtual bool TauFinder::operator()(PixieFunctionParms<int>&)’:
/home/pixie16/Programs/PixieSuite2/Interface/source/PixieSupport.cpp:370: error: invalid conversion from ‘double_’ to ‘short unsigned int’
/opt/xia/current/software/app/pixie16app_export.h:203: error: too few arguments to function ‘int Pixie16TauFinder(short unsigned int, short unsigned int, double_)’
/home/pixie16/Programs/PixieSuite2/Interface/source/PixieSupport.cpp:370: error: at this point in file
make[2]: **\* [Interface/source/CMakeFiles/PixieSupport.dir/PixieSupport.cpp.o] Error 1
make[1]: **\* [Interface/source/CMakeFiles/PixieSupport.dir/all] Error 2
make: **\* [all] Error 2

SOL: 

commented out TauFinder and references to it in:
 in PixieSupport.cpp , find_tau.cpp, and poll2_core.cpp

Notes: 
home/pixie16/Programs/PixieSuite2/Setup/source/find_tau.cpp: In function ‘int main(int, char**)’:
/home/pixie16/Programs/PixieSuite2/Setup/source/find_tau.cpp:18: warning: unused variable ‘mod’
/home/pixie16/Programs/PixieSuite2/Setup/source/find_tau.cpp:19: warning: unused variable ‘ch’
and 
CMakeFiles/poll2.dir/poll2_core.cpp.o: In function `Poll::CommandControl()':
poll2_core.cpp:(.text+0xc143): undefined reference to`vtable for TauFinder'
collect2: ld returned 1 exit status
/home/pixie16/Programs/PixieSuite2/Poll/source/poll2_core.cpp: In member function ‘void Poll::CommandControl()’:
/home/pixie16/Programs/PixieSuite2/Poll/source/poll2_core.cpp:1139: warning: unused variable ‘mod’
/home/pixie16/Programs/PixieSuite2/Poll/source/poll2_core.cpp:1140: warning: unused variable ‘ch’
1. USER ERROR: 

/usr/bin/ld: cannot find -lPlxApi
SOL:

fixed broxen link in test directory 
1. NEW? ERROR:

../../Interface/source/libPixieInterface.a(PixieInterface.cpp.o): In function `PixieInterface::PixieInterface(char const*)':
PixieInterface.cpp:(.text+0x37f4): undefined reference to`PCISysIniFile'
collect2: ld returned 1 exit status
make[2]: **\* [MCA/source/MCA] Error 1
make[1]: **\* [MCA/source/CMakeFiles/MCA.dir/all] Error 2
make: **\* [all] Error 2

SOL:

Added _Linux to line : 20
extern const char\* PCISysIniFile_Linux;

Added _Linux to line : 129
PCISysIniFile_Linux = configStrings["CrateConfig"].c_str();

In this ver. of the PXI libraries software_plx6.40 expected *_Windows or *_Linux instead of 'PCISysIniFile' name

Used:

cmake ../ -DCMAKE_INSTALL_PREFIX=/opt/PixieSuite2 -DUSE_ROOT=OFF -DUSE_SETUP=ON -DPLX_LIBRARY_DIR=/opt/plx/current

make and make install run with the above warnings and additionally:
/home/pixie16/Programs/PixieSuite2/MCA/source/HisDrr.cpp: In constructor ‘HisDrr::HisDrr(const std::string&, const std::string&, const std::string&)’:
/home/pixie16/Programs/PixieSuite2/MCA/source/HisDrr.cpp:153: warning: ‘totLength’ may be used uninitialized in this function

Set 
CrateConfig pxisys.ini //changed in pixie.cfg 
this was related to '_Linux' Error 

I will be continuing to test this next week when I am there.

**Comment by ksmith0** [comment]
I'm not surprised by the NEW ERROR we should find a way to detect the version of the PXI libraries and then use that as a precompiler test and choose which code to use. This would resolve the known error as well. After renaming the extern I do not think it is necessary to reconfigure CrateConfig in pixie.cfg.

**Comment by ksmith0** [comment]
@spaulaus Can we label this will not fix? At this point I believe we have mostly transitioned to PLX 7.

**Comment by ksmith0** [comment]
@ntbrewer Why did you close this? Was the issue resolved?

**Comment by ntbrewer** [comment]
Solutions implemented for our setup are listed. It seemed like this was a
specific case and could be closed.

N
