### ISSUE TITLE
Issue in CFDTuner Branch

### ISSUE THREAD

**Issue by spaulaus** [pixie16/PixieSuite2#90]
Commit: 029324d80dd1c280db92c813e1d7605fe85d9229

When running the cfdtuner program it successfully scanned the input file, however at the end of the file the program hung and did not quit cleanly. I had to Ctrl+C to kill the program, and my terminal text is now colored green. I suspect that this is because this file was not closed properly when it was taken and is missing the EOF marker.

**Comment by cthornsb** [comment]
I can't reproduce this issue. Everything seems to be working. Scanning an arbitrary ldf file gives 

Cleaning up...
CfdTuner: Found 20545 traces and processed 0.

Followed by a clean exit. As far as the terminal corruption, cfdtuner is in batch mode by default and doesn't use an interactive terminal. I don't understand why it would cause your terminal would turn green.

**Comment by spaulaus** [comment]
Try with the following file from kqxhc:
/data/utk/vandleDev/2016/skutek/sipmSkutek_001.ldf

**Comment by cthornsb** [comment]
That did the trick. I've encountered this problem before. Unfortunately, the issue lies inside hribf_buffers... I'm working today on cleaning up the ::read methods for ldf files. This problem does not arise for new ldf files written by poll2, so I suspect the problem may be the way event fragments were stored in the ldf files by original poll??? If this turns out to be the case, a quick solution would probably be to skip the problematic partial events.

**Comment by spaulaus** [comment]
Interesting. I will continue without using this file as a reference then.

**Comment by cthornsb** [comment]
In the mean time, I suggest recording a simple ldf file with poll2 and using that for testing purposes.

**Comment by spaulaus** [comment]
We have one already, I just didn't have it handy this morning.

**Comment by spaulaus** [comment]
Try running the data file we took on 04/20/2016, please.

 /data/utk/plsr/2016/04-20/pulser2ns_001.ldf

**Comment by cthornsb** [comment]
This issue is addressed in commit 2d83a24. It seems that the problem arises from missing and/or corrupted spill chunks. The old read method would get to a missing chunk and hang or get to a corrupted chunk and crash.

**Comment by cthornsb** [comment]
This is probably why I haven't seen this problem until now. Encountering missing chunks is unlikely when scanning a file written by poll2. But scanning a file written by pacman may have multiple missing chunks due to packet losses over the network.

**Comment by spaulaus** [comment]
Great, closing issue.
