### ISSUE TITLE
Terminal goto statements

### ISSUE THREAD

**Issue by ksmith0** [pixie16/PixieSuite2#95]
The terminal is using goto statements ever since commit 4f59ee4781b60b61, which added the ability to handle scripts. We agree that the script feature is useful and should be maintained, but we would like a new implementation to avoid the goto statements and reduce the clutter int he parser. There was a small discussion in the comments of the commit b507ae4fe99aa67.

**Comment by cthornsb** [comment]
Resolved in commit 6eb40d6 to dev branch.

**Comment by cthornsb** [comment]
This commit also fixes a seg-fault related to the goto statements when poll2 is run in pacman mode.
